### ISSUE TITLE
Deprecation warning for Node 12

### ISSUE THREAD

**Issue by fargito** [nwtgck/actions-netlify#837]
Hello, and thanks a lot for this awesome action!

I have started encountering this warning in my CI lately:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: nwtgck/actions-netlify
```
Is the update to Node 16 on the roadmap?

**Comment by nwtgck** [comment]
Thanks for notifying me.

**Comment by nwtgck** [comment]
Thank you so much for the investigation! Bumping up libraries is repository maintainer's task for security reason. I'll try.

**Comment by nwtgck** [comment]
This should  be resolved by https://github.com/nwtgck/actions-netlify/pull/827.

I released 1.2.4.

**Comment by fargito** [comment]
I can confirm, the issue is resolved on my end as well. Thanks a lot!

**Comment by kfiven** [comment]
@nwtgck Hi, I am [still getting](https://github.com/cinnyapp/cinny/actions/runs/3420494219) the Node 12 error on [v1.2.4](https://github.com/cinnyapp/cinny/pull/920).
